FROM nvidia/cuda:12.1.0-devel-ubuntu18.04

RUN apt update \
    && apt install -y wget \
    && apt install -y git \
    && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /root/miniconda3 \
    && /root/miniconda3/condabin/conda create --name py10 python==3.10 \
    && echo ". /root/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc \
    && echo "conda activate py10" >> ~/.bashrc && mkdir /root/data/

RUN git clone https://github.com/AwsomeName/easy_nlp.git
RUN /root/miniconda3/envs/py10/bin/pip install -r easy_nlp/starcode/chat/requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
RUN /root/miniconda3/envs/py10/bin/pip install -r easy_nlp/starcode/requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
# RUN python api.py
RUN pip install git+https://github.com/huggingface/transformers.git@main accelerate



